import { buildTheme, type ThemeBundle } from './css';
import { M3E_COLOR_ROLES } from './roles';
import { MOTION_DURATIONS, MOTION_EASINGS, MOTION_SPRINGS } from './motion';
import { SHAPE_SIZES, NAMED_SHAPES } from './shape';
import { TYPE_ROLES } from './typography';
import { shapeSizePx } from './shape';
import type { M3EConfig } from './config';

/** W3C DTCG-style design tokens JSON for the current config. */
export function generateTokensJson(input: M3EConfig): string {
  const bundle: ThemeBundle = buildTheme(input);
  const { config } = bundle;
  const p = config.naming === 'md-sys' ? 'md-sys' : 'm3e';

  const color = (vars: ThemeBundle['light']) =>
    Object.fromEntries(
      M3E_COLOR_ROLES.map((role) => [
        role,
        { $value: vars[`--${p}-color-${role}`], $type: 'color' },
      ]),
    );

  const json = {
    name: 'Material 3 Expressive theme',
    description: `Generated by M3E Studio (seed ${config.seed}, variant ${config.variant})`,
    $extensions: {
      'io.material.studio': {
        seed: config.seed,
        variant: config.variant,
        contrast: config.contrast,
        shapeEmphasis: config.shapeEmphasis,
        cornerBoost: config.cornerBoost,
        motionScheme: config.motionScheme,
        typeScale: config.typeScale,
      },
    },
    color: { light: color(bundle.light), dark: color(bundle.dark) },
    shape: {
      corner: Object.fromEntries(
        (Object.keys(SHAPE_SIZES) as (keyof typeof SHAPE_SIZES)[]).map((name) => [
          name,
          { $value: `${shapeSizePx(name, config.shapeEmphasis)}px`, $type: 'dimension' },
        ]),
      ),
      named: Object.fromEntries(
        Object.keys(NAMED_SHAPES).map((name) => [
          name,
          { $value: bundle.shared[`--${p}-shape-${name}`], $type: 'dimension' },
        ]),
      ),
    },
    typography: Object.fromEntries(
      TYPE_ROLES.map((role) => [
        role,
        {
          $value: {
            fontFamily: `var(--${p}-typescale-${role}-font)`,
            fontSize: `var(--${p}-typescale-${role}-size)`,
            lineHeight: `var(--${p}-typescale-${role}-line-height)`,
            letterSpacing: `var(--${p}-typescale-${role}-letter-spacing)`,
            fontWeight: `var(--${p}-typescale-${role}-weight)`,
          },
          $type: 'typography',
        },
      ]),
    ),
    motion: {
      duration: Object.fromEntries(
        Object.entries(MOTION_DURATIONS).map(([name, ms]) => [
          name,
          { $value: `${ms}ms`, $type: 'duration' },
        ]),
      ),
      easing: Object.fromEntries(
        Object.entries(MOTION_EASINGS).map(([name, c]) => [
          name,
          { $value: { x1: c[0], y1: c[1], x2: c[2], y2: c[3] }, $type: 'cubicBezier' },
        ]),
      ),
      spring: {
        expressive: Object.fromEntries(
          Object.entries(MOTION_SPRINGS.expressive).map(([u, s]) => [
            u,
            {
              $value: { stiffness: s.stiffness, damping: s.damping, mass: 1 },
              $type: 'other',
              $extensions: { 'io.material.spring': true },
            },
          ]),
        ),
        standard: Object.fromEntries(
          Object.entries(MOTION_SPRINGS.standard).map(([u, s]) => [
            u,
            {
              $value: { stiffness: s.stiffness, damping: s.damping, mass: 1 },
              $type: 'other',
              $extensions: { 'io.material.spring': true },
            },
          ]),
        ),
      },
    },
  };

  return JSON.stringify(json, null, 2) + '\n';
}
